spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

    h2:
      console:
        enabled: true
        path: /h2-console

    jpa:
      defer-datasource-initialization: true
      show-sql: true
      properties:
        hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: <username>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kc.sead.ufes.br:8443/realms/sead-ufes
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

erp:
  mail:
    fest:
      recipients: bonnie@gmail.com,clyde@gmail.com
